nodeLinker: node-modules

npmRegistries:
  //git.etaminstud.io/api/v4/packages/npm:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN-fallback}"

npmScopes:
  etaminstudio:
    npmRegistryServer: "https://git.etaminstud.io/api/v4/packages/npm"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
